
# Setup
title:               Kube-Router
email:               muralimmreddy@gmail.com
tagline:             Turnkey Kubernetes networking solution
url:                 "https://kube-router.io" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Murali Reddy
  url:               https://in.linkedin.com/in/murali-reddy-3759574
  email:             muralimmreddy@gmail.com

# Social
github_username: thundergolfer
twitter_username: 3rdwave_themes
instagram_username: kevin/
facebook: 3rdwavethemes/
linkedin_username: xiaoying
dribbble_username: Xiaoying

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

exclude: kube-router

widgets:
  - title: Github
    url: "https://github.com/cloudnativelabs/kube-router"
    archor: false
  - title: Documentation
    url: "https://www.kube-router.io/docs"
    archor: false
  - title: Blog
    url: "https://cloudnativelabs.github.io"
    archor: false
