# Project information
site_name: Kube-router
site_description: "Kube-router: a turnkey Kubernetes networking solution"
site_author: "Kube-router Project"
site_url: https://github.com/cloudnativelabs/kube-router


# Repository
repo_name: kube-router
repo_url: https://github.com/cloudnativelabs/kube-router
edit_uri: ""
docs_dir: "kube-router/docs"

# Theme and overrides, i.e. language partial
theme:
  name: "rtd-dropdown"

# Page tree
pages:
  - Overview: index.md
  - Concepts:
    - How it works: how-it-works.md
    - See it in action: see-it-in-action.md
    - Architecture: architecture.md
  - Installation:
    - Generic: generic.md
    - BootKube: bootkube.md
    - Kops: kops.md
    - Kubeadm: kubeadm.md
  - Usage:
    - BGP: bgp.md
  - Operations:
    - Health: health.md
    - Metrics: metrics.md
    - Upgrading: upgrading.md
    - Toolbox: pod-toolbox.md
  - Development:
    - Developing: developing.md
    - Testing: testing.md

